version: "3.3"
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: always
    user: "1000"
    volumes:
       - ./grafana/data/:/var/lib/grafana/
       - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini

  loki:
    image: grafana/loki:2.6.1
    restart: always
    user: "1000"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config/config.yml:/etc/loki/local-config.yaml
      - ./loki/data/:/data/

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/log:/var/log
      - ./promtail/config/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "1514:1514"
