mqtt:
  host: mqtt
cameras:
  lab_elektroniczny:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_ELAB_RTSP}
          roles:
            - detect
            - record
  softroom:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_SOFTROOM_RTSP}
          roles:
            - detect
            - record
detectors:
  cpu1:
    type: cpu
    num_threads: 3

detect:
  width: 640
  height: 360
objects:
  track:
    - person
record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 5
    objects:
      - person
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain:
    default: 100