mqtt:
  host: mqtt
cameras:
  lab_elektroniczny:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_ELAB_RTSP}
          roles:
            - detect
            - record
  softroom:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_SOFTROOM_RTSP}
          roles:
            - detect
            - record
  hardroom_na_drzwi:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_HARDROOM_NA_DRZWI_RTSP}
          roles:
            - detect
            - record
  hardroom_od_drzwi:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_HARDROOM_OD_DRZWI_RTSP}
          roles:
            - detect
            - record
  korytarz:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_KORYTARZ_RTSP}
          roles:
            - detect
            - record
  korytarz_wyjscie:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_KORYTARZ_WYJSCIE_RTSP}
          roles:
            - detect
            - record
  magazynek:
  # this is an mjpeg camera, it needs transcoding
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: rtsp://{FRIGATE_MAGAZYNEK_RTSP}
          roles:
            - detect
            - record
  magazynek2:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_MAGAZYNEK2_RTSP}
          roles:
            - detect
            - record
  
detectors:
  cpu1:
    type: cpu
    num_threads: 3

detect:
  width: 640
  height: 360
objects:
  track:
    - person
record:
  enabled: True
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 5
    objects:
      - person
snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain:
    default: 100
