mqtt:
  host: mqtt
cameras:
  lab_elektroniczny:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_ELAB_RTSP}
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
    record:
      enabled: True
      events:
        retain:
          default: 5
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 100
  softroom:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_SOFTROOM_RTSP}
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
    objects:
      track:
        - person
    record:
      enabled: True
      events:
        retain:
          default: 5
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 100

detectors:
  cpu1:
    type: cpu
    num_threads: 3
